In [2]:
import numpy as np
import pandas as pd

#### Foundations for efficiencies

In [3]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']


In [4]:
# Rewrite the for loop to use enumerate
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i, name) for i, name in enumerate(names)]
print(indexed_names_comp)

# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [*enumerate(names, 1)]
print(indexed_names_unpack)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


In [6]:
# Use map to apply str.title to each element in names
names_map  = map(str.title, names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase = [* names_map]

# Print the list created above
print(names_uppercase)

<class 'map'>
['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']


In [10]:
nums2 = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]

In [11]:
nums = np.array(nums2)

In [13]:
# Print second row of nums
print(nums[1,:])
print(("--------------------------------"))
# Print all elements of nums that are greater than six
print(nums[nums > 6])
print(("--------------------------------"))
# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)
print(("--------------------------------"))
# Replace the third column of nums
nums[:,2] = nums[:,2] + 1
print(nums)

[4 5 7]
--------------------------------
[ 7  7  8 10]
--------------------------------
[[ 2  4  8]
 [ 8 10 14]
 [14 16 20]]
--------------------------------
[[ 1  2  5]
 [ 4  5  8]
 [ 7  8 11]]


In [15]:
# Use the unpacking operator to create a list from the range object
arrival_times = [*range(10, 60, 10)]

print(arrival_times)

[10, 20, 30, 40, 50]


In [14]:
# Use the unpacking operator to create a list from the range object
arrival_times = [i for i in range(10, 60, 10)]

print(arrival_times)

[10, 20, 30, 40, 50]


In [19]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

# Map the welcome_guest function to each (guest,time) pair




In [20]:
def welcome_guest(guest_time):
    name, time = guest_time
    return f"Welcome {name}! You arrive at {time} minutes."

In [21]:
welcome_map = map(welcome_guest, guest_arrivals)
guest_welcomes = [*welcome_map]
print(*guest_welcomes, sep='\n')

Welcome Jerry! You arrive at 7 minutes.
Welcome Kramer! You arrive at 17 minutes.
Welcome Elaine! You arrive at 27 minutes.
Welcome George! You arrive at 37 minutes.
Welcome Newman! You arrive at 47 minutes.


#### Timing and profiling code
"useful built-in modules for writing efficient code and practice using set theory"